def board():
    board = [
        {'N': False, 'E': True, 'S': True, 'W': False, 'item': None},
        {'N': True, 'E': False, 'S': True, 'W': False, 'item': None},
        {'N': False, 'E': True, 'S': True, 'W': True, 'item': 0},
        {'N': True, 'E': True, 'S': False, 'W': False, 'item': 17},
        {'N': False, 'E': True, 'S': True, 'W': True, 'item': 1},
        {'N': True, 'E': False, 'S': True, 'W': True, 'item': 23},
        {'N': False, 'E': False, 'S': True, 'W': True, 'item': None},
        {'N': True, 'E': True, 'S': False, 'W': True, 'item': 19},
        
        {'N': True, 'E': False, 'S': True, 'W': False, 'item': None},
        {'N': False, 'E': False, 'S': True, 'W': True, 'item': None},
        {'N': True, 'E': True, 'S': False, 'W': True, 'item': 22},
        {'N': True, 'E': False, 'S': False, 'W': True, 'item': 15},
        {'N': False, 'E': True, 'S': False, 'W': True, 'item': None},
        {'N': True, 'E': True, 'S': False, 'W': True, 'item': 18},
        {'N': True, 'E': True, 'S': True, 'W': False, 'item': 2},
        {'N': False, 'E': False, 'S': True, 'W': True, 'item': None},
        {'N': True, 'E': True, 'S': True, 'W': False, 'item': 3},
        {'N': True, 'E': False, 'S': True, 'W': False, 'item': None},
        {'N': False, 'E': True, 'S': True, 'W': True, 'item': 4},
        {'N': False, 'E': True, 'S': False, 'W': True, 'item': None},
        {'N': True, 'E': False, 'S': True, 'W': True, 'item': 5},
        {'N': False, 'E': True, 'S': False, 'W': True, 'item': None},
        {'N': True, 'E': False, 'S': False, 'W': True, 'item': None},
        {'N': False, 'E': False, 'S': True, 'W': True, 'item': None},
        {'N': False, 'E': False, 'S': True, 'W': True, 'item': None},
        {'N': False, 'E': True, 'S': False, 'W': True, 'item': None},
        {'N': False, 'E': True, 'S': True, 'W': False, 'item': None},
        {'N': False, 'E': True, 'S': True, 'W': False, 'item': None},
        {'N': True, 'E': True, 'S': True, 'W': False, 'item': 6},
        {'N': False, 'E': True, 'S': True, 'W': False, 'item': None},
        {'N': True, 'E': True, 'S': False, 'W': True, 'item': 7},
        {'N': True, 'E': False, 'S': True, 'W': False, 'item': None},
        {'N': True, 'E': False, 'S': True, 'W': True, 'item': 8},
        {'N': True, 'E': False, 'S': True, 'W': False, 'item': None},
        {'N': True, 'E': False, 'S': True, 'W': True, 'item': 9},
        {'N': False, 'E': True, 'S': False, 'W': True, 'item': None},
        {'N': True, 'E': True, 'S': False, 'W': False, 'item': None},
        {'N': True, 'E': False, 'S': True, 'W': True, 'item': 21},
        {'N': False, 'E': False, 'S': True, 'W': True, 'item': 13},
        {'N': True, 'E': False, 'S': True, 'W': False, 'item': None},
        {'N': True, 'E': False, 'S': False, 'W': True, 'item': 14},
        {'N': True, 'E': False, 'S': True, 'W': True, 'item': 20},
        {'N': True, 'E': True, 'S': False, 'W': False, 'item': None},
        {'N': True, 'E': True, 'S': False, 'W': False, 'item': None},
        {'N': True, 'E': True, 'S': False, 'W': True, 'item': 10},
        {'N': True, 'E': False, 'S': True, 'W': False, 'item': None},
        {'N': True, 'E': True, 'S': False, 'W': True, 'item': 11},
        {'N': True, 'E': True, 'S': False, 'W': False, 'item': 12},
        {'N': True, 'E': False, 'S': False, 'W': True, 'item': None}
    ]
    return board